name: vizd
version: '2.3.0'
summary: Full node for VIZ network
description: |
  DAO (decentralized autonomous organization), where the blockchain itself is managed by the holders of shares

grade: stable
confinement: strict

apps:
  vizd:
    command: bin/vizd -d '$SNAP_USER_DATA'/witness_node_data_dir --resync-blockchain
    plugs:
      - network
      - home
      - network-bind

  vizd-rb:
    command: bin/vizd -d '$SNAP_USER_DATA'/witness_node_data_dir --replay-blockchain
    plugs:
      - network
      - home
      - network-bind

  vizd-rc:
    command: bin/vizd -d '$SNAP_USER_DATA'/witness_node_data_dir --replay-if-corrupted
    plugs:
      - network
      - home
      - network-bind

  vizd-wallet:
    command: bin/cli_wallet -d '$SNAP_USER_DATA'/wallet --resync
    plugs:
      - network
      - home
      - network-bind

parts:
  viz:
    plugin: cmake
    configflags:
       - -DCMAKE_BUILD_TYPE=Release

    override-pull: |
       git clone https://github.com/VIZ-World/viz-world.git .
       git checkout dev-hf7
       git submodule update --init --recursive

    build-packages:
       - build-essential
       - autoconf
       - automake
       - cmake
       - g++
       - libssl-dev
       - libtool
       - make
       - pkg-config
       - python3
       - python3-jinja2
       - libboost-chrono-dev
       - libboost-context-dev
       - libboost-coroutine-dev
       - libboost-date-time-dev
       - libboost-filesystem-dev
       - libboost-iostreams-dev
       - libboost-locale-dev
       - libboost-program-options-dev
       - libboost-serialization-dev
       - libboost-signals-dev
       - libboost-system-dev
       - libboost-test-dev
       - libboost-thread-dev
       - doxygen
       - libncurses5-dev
       - libreadline-dev
       - perl
